AspNetCore/AspNetCore/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCore.Models
{
    public class Student
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Eesnimi on kohustuslik")]
        [StringLength(10, MinimumLength = 5, ErrorMessage = "5-10 tähte")]
        [Display(Name = "First name")]
        //need sõnumid ja pealkirjad on kogu aeg FirstNamega seotud, ka edit meetodis (kui tahan studenti editida
        //ja nt tahan nime kustutada, tuleb sama errormessage. ainult see seobki, et ta on enne meetodit [] sulgudes
        public string FirstName { set; get; }
        [Display(Name = "Last name")]
        public string LastName { get; set; }
        [Range(1, 35, ErrorMessage = "Vanus peab olema 1 ja 35 vahel")]
        public int? Age { get; set; }
        [Display(Name = "Marriage status (married - true; not married  - false")]
        public bool? IsMarried { get; set; }
        [Display(Name = "Blind?")]
        public bool IsBlind { get; set; }

        public List<Loan> Loans { get; set; }

        [NotMapped] //ComponentModel.DataAnnotations.Schema;
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }

        public byte[] Picture { get; set; }
    }
}

AspNetCore/AspNetCore/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCore.Data;
using AspNetCore.Models;
using System.Security.Claims;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace AspNetCore.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        //context on viide
        public StudentsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult HelloName(string name, int count)
        {
            string text = "";
            for (int i = 0; i < count; i++)
            {
                text += "Hello " + name + Environment.NewLine;
            }
            return Content(text);
        }

        //https://localhost:44393/Students/helloname?name=Marilyn&count=7 - selle aadressiga on nagu käsk,
        //et printi 7 korda Hello + valitud nimi




        // GET: Students
        public IActionResult Index()
        {

            //Kasutaja kontrollimine Id järgi:
            if (User.Identity.IsAuthenticated)
            {
                var users = _userManager.Users.Where(x => x.FirstName != "Kalle").ToList();
                users = _context.Users.Where(x => x.FirstName != "Kalle").ToList();

                ViewData["Name"] = User.Identity.Name;
                string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }

            //Sel hetkel, kui ma käivitan .ToList()
            //Tehakse tegelikult päring andmebaasi
            //SELECT * FROM Student
            //
            var students = _context.Student
                .OrderBy(x => x.LastName)
                .ThenBy(x => x.FirstName)
                .ToList();
            
            //Select Age, FirstName FROM Student

            var firstName = (from student in students//küsin omakorda eelmiselt vahetulemuselt, mitte andmebaasilt
                             where student.Age < 30
                             select new Student()
                             {
                                 Age = student.Age,
                                 FirstName = student.FirstName
                                }
                        ).ToList();
            return View(students);
            
        }

        // GET: Students/Details/5
        [Authorize(Roles = "Admin,HR")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        //Bind määrab ära propertied, mis tulevad sellesse meetodisse kaasa
        public async Task<IActionResult> Create(int id, [Bind("Id,FirstName,LastName,Age")] Student student)
        {
            if (ModelState.IsValid) // see tähendab kui kõik student atribuudid on õiged (nimi on olemas ja vanus int jne)
                //kontroll kas kõik väljas valideeris
            {
                // Add meetod on uue rea lisamiseks tabelisse
                // INSERT INTO student

                _context.Add(student);
                await _context.SaveChangesAsync();
                return Json(student);
            }
            return StatusCode(500, "Error occured");
        }


        public IActionResult GetImageFile(int studentId)
        {
            var student = _context.Student.Find(studentId);
            if(student.Picture == null)
            {
                return Content("Pilti pole");
            }
            return File(student.Picture, "image/jpg");
        }

        public IActionResult SumLoans()
        {
            return Content(Convert.ToString(_context.Loan.Sum(x => x.Amount)));
        }
        // GET: Students/Edit/5

            // int? tähendab, et see on int tüüp, mis lisaks võib olla ka null
            // Nullable
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                //404 errori lehe näitamine
                return NotFound();
            }
            //Find on nagu FirstOrDefault, aga otsib ainult Primary Key järgi
            var student =  _context.Student.Find(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Bind määrab ära propertied, mis tulevad sellesse meetodisse kaasa
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Age")] Student student, IFormFile picture)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid) // see tähendab kui kõik student atribuudid on õiged (nimi on olemas ja vanus int jne)
                                    //kontroll kas kõik väljas valideeris
            {
                try //proovib teha
                {
                    // UPDATE Student
                    //SET FirstName = student.FirstName,
                    //      LastName = student.LastName
                    //      Age = student.Age
                    // ..................
                    // WHERE
                    //    Id = student.Id
                    // Kui primary Key student.Id = 0
                    // siis tegelikult tehakse hoopis INSERT
                    // UPDATE ei kirjutata veel andmebaasi
                    // Kirjutatakse alles siis, kui kutsutakse
                    // SaveChangesAsync()

                    //Faili üles laetud pildi salvestamine
                    //FileStream stream = new FileStream("Cat03.jpg", FileMode.Create, FileAccess.Write);
                    //picture.CopyTo(stream);
                    //stream.Close();

                    MemoryStream stream = new MemoryStream();
                    picture.CopyTo(stream);
                    student.Picture = stream.ToArray();
                    stream.Close();

                    _context.Update(student);
                    _context.SaveChanges();
                }


                catch (DbUpdateConcurrencyException) //ja kui ei õnnestu siis
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound(); // 404 error
                    }
                    else // kui juhtus exception (mingi muu kui et pole kasutajat)
                    {
                        throw; // viska uuesti seesama exception mis enne püüdsin. sama hea kui et polegi catchi teinud
                    }
                }
                // Suunab edasi kindla Actionini
                // nameof(index) annab mulle kindla stringina Index actioni nime
                // Index kohale saab panna ainult neid actioneid, mis tõesti olemas
                return RedirectToAction(nameof(Index));  
            }
            // Võta seesama student objekt (uute andmetega) ja täida
            // sama view uuesti samade andmetega
            // Lisaks tulevad siia valideerimise veateated
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Student.FindAsync(id);
            _context.Student.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteStudent(int id)
        {
            var student = await _context.Student.FindAsync(id);
            _context.Student.Remove(student);
            await _context.SaveChangesAsync();
            return Json(id);
        }

        private bool StudentExists(int id)
        {
            var student = _context.Student.Where(x => x.Id == id); //leia mulle selle id'ga esimene student
            if (student == null) //kui sulge ei pane, läheb if blokki ainult esimene rida. seega soovituslik on ikka sulgudega
            //{
                return false;
            //}
            return true;

            //return _context.Student.Any(e => e.Id == id); //kas on üldse sellise id-ga
        }
    }
}

AspNetCore/AspNetCore/Views/Students/Create.cshtml
@model AspNetCore.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsMarried" class="control-label"></label>
                @Html.EditorFor(model => model.IsMarried)
                @*<input asp-for="IsMarried" class="form-control" />*@
                <span asp-validation-for="IsMarried" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AspNetCore/AspNetCore/Views/Students/Delete.cshtml
@model AspNetCore.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AspNetCore/AspNetCore/Views/Students/Details.cshtml
@model AspNetCore.Models.Student

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AspNetCore/AspNetCore/Views/Students/Edit.cshtml
@model AspNetCore.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Student</h4>
<hr />

@if (Model.Picture != null)
{

}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*
        asp-for annab antud mudeli mingi väärtuse
        antud juhul If väärtuse
            *@
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*
            asp-for="FirstName" - anna välja FirstName nimetus
                *@
                <label asp-for="LastName" class="control-label"></label>
                @* *@
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">

                @*drop-down menüü true-false, kus default on "not set"*@
                <label asp-for="IsMarried" class="control-label"></label>
                @Html.EditorFor(model => model.IsMarried)
                @*<input asp-for="IsMarried" class="form-control" />*@
                <span asp-validation-for="IsMarried" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsBlind" class="control-label"></label>
                <input asp-for="IsBlind" class="form-control" />
                <span asp-validation-for="IsBlind" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input type="file" name="Picture" id="Picture" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AspNetCore/AspNetCore/Views/Students/Index.cshtml
@*
    <strongly typed view
    Siia viewsse saan ma ainult panna kaasa @model taga kirjeldatud tüüpi objekti
*@

@model IEnumerable<AspNetCore.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a href="http://www.delfi.ee">DELFI</a>
    <br /> <!-- ilma sisuta tag -->
    @* Tag helpers
        Tee mulle link, mis suunab Create Actionisse
        Kui pole eraldi määratud, siis võetakse sama kontrolleri Action, kus me viibime
        asp-action ütleb actioni
        asp-controller ütleb kontrolleri
    *@
    <a asp-action="Create" asp-controller="Students">Create New</a>
    <br />
    @*@Html.ActionLink("Create New", "Create", "Students") - sama mis eelnev*@
</p>
<table class="table">
    <thead>
        <tr>
            @*DisplayNameFor annab tabeli veergudele pealkirjad*@
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @* HTML helpers
                    DisplayNameFor annab mulle mudeli mingi konkreetse välja ehk klassi property
                    "FirstName"
                *@
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsMarried)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @*Html.DisplayFor annab välja (väli) väärtuse*@
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsMarried)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Picture)
                </td>
                <td>
                    @* asp-route-id ütleb siis, et Edit action pane kaasa parameeter id
                        ehk peale teist kaldkriipsu kolmas parameeter
                        /Students/Edit/4*@
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    @{var id = "link" + item.Id; // link_1 link_2
                    }
                    <a href='' id="'@id" class='linkDeleteStudent'>Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<input type="button" value="Sum loans" id="buttonSum" />
<input type="button" value="" id="buttonSum" />

<div id="result"></div>
@section Scripts
    {
    <script type="text/javascript">


        $(document).ready(function () {
            $('#buttonSum').click(function () {
                $ajax({
                    type: 'GET',
                    url: '@Url.Action("AddStudent")','/Students/SumLoans',
                    success: function (result) {
                        // Tavaline javascript sama asja tegemiseks
                        // document.getElementById.
                        $('#result1').html(result);
                        $('#studentsTableBody').append("<tr><td>3</td><td>Peeter</td><td>Paan</td></tr>")
                    }
                });
            });
            $('#buttonAddStudent').click(function () {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Create")', // Students/Create
                    data: {
                        firstName: "Peeter",
                        lastName: "Paan",
                        age: 30,
                        isMarried: "true",
                    },
                    success: function (result) {
                        $('#studentsTableBody').append("<tr><td>3</td><td>Peeter</td><td>Paan</td><td>30</td><td></td></tr>");
                    },
                    error: function (xhr, status, error) {
                        $('#result').html(xhr.responseText);
                    }

                });
            });
        });
    </script>
}